 apiVersion: apps/v1
 kind: Deployment
 metadata:
   name: expense
 spec:
   replicas: 1
   selector:
     matchLabels:
       app: flasknode
   template:
     metadata:
       labels:
         app: flasknode
     spec:
       containers:
       - name: flasknode
         image: icr.io/shrimathi/wallet
         imagePullPolicy: Always
         ports:
         - containerPort: 8080